### ISSUE TITLE
Project assesment 

### ISSUE THREAD

**Issue by Mikelabu** [jwri211/openSauce#4]
We need to start thinkinmg of a Design soloution for our assessment .

PART 1. SOLUTION DESIGN
 Task 1. Design solution
 Task 2. Define business model 
Both tasks are done in parallel and iteratively, following the Build – Measure – Learn model of the 
Lean Start-up:
 Build: from first sketches to a mockup or prototype
 Measure: deliver first drafts / prototypes early, get feedback
 Learn: learn from mistakes, correct, adjust, improve

**Comment by jwri211** [comment]
Definitely. But first, let's identify a problem to be solved as per the "Workshop" assessment.
